return {
	keyCommands = {
		{combos = {{key = 'H', reformers = {'LAlt'}}}, down = iCommandViewCameraMoveHorizontal, name = _('Horizontal camera moving'), category = _('View')},
		{combos = {{key = 'V', reformers = {'LAlt'}}}, down = iCommandViewCameraMoveVertical, name = _('Vertical camera moving'), category = _('View')},
		{combos = {{key = 'F', reformers = {'LAlt'}}}, down = iCommandViewCameraMoveFrontal, name = _('Frontal camera moving'), category = _('View')},
		{combos = {{key = 'G', reformers = {'LAlt'}}}, down = iCommandViewAtGround, name = _('Direct the camera towards the ground'), category = _('View')},
		{combos = {{key = 'N', reformers = {'LAlt'}}}, down = iCommandViewCameraWorldAxes, name = _('Direct the camera along world axes'), category = _('View')},
		-- Camera position to/from clipboard 
		{combos = {{key = 'C', reformers = {'LShift'}}}, down = iCommandViewCameraToClipboard, name = _('Unload camera position to clipboard'), category = _('View')},
		{combos = {{key = 'V', reformers = {'LShift'}}}, down = iCommandViewClipboardToCamera, name = _('Load camera position from clipboard'), category = _('View')},
		-- WASDEQ keys
		{combos = {{key = 'W'}}, pressed = iCommandViewKeyW, up = iCommandViewKeyWStop, name = _('Forward key W'), category = _('View')},
		{combos = {{key = 'S'}}, pressed = iCommandViewKeyS, up = iCommandViewKeySStop, name = _('Backward key S'), category = _('View')},
		{combos = {{key = 'A'}}, pressed = iCommandViewKeyA, up = iCommandViewKeyAStop, name = _('Left key A'), category = _('View')},
		{combos = {{key = 'D'}}, pressed = iCommandViewKeyD, up = iCommandViewKeyDStop, name = _('Right key D'), category = _('View')},
		{combos = {{key = 'W', reformers = {'LShift'}}}, pressed = iCommandViewKeyLShiftW, up = iCommandViewKeyLShiftWStop, name = _('Fast forward key LShift-W'), category = _('View')},
		{combos = {{key = 'S', reformers = {'LShift'}}}, pressed = iCommandViewKeyLShiftS, up = iCommandViewKeyLShiftSStop, name = _('Fast backward key LShift-S'), category = _('View')},
		{combos = {{key = 'A', reformers = {'LShift'}}}, pressed = iCommandViewKeyLShiftA, up = iCommandViewKeyLShiftAStop, name = _('Fast left key LShift-A'), category = _('View')},
		{combos = {{key = 'D', reformers = {'LShift'}}}, pressed = iCommandViewKeyLShiftD, up = iCommandViewKeyLShiftDStop, name = _('Fast right key LShift-D'), category = _('View')},
		{combos = {{key = 'W', reformers = {'LCtrl'}}}, pressed = iCommandViewKeyLCtrlW, up = iCommandViewKeyLCtrlWStop, name = _('Slow forward key LCtrl-W'), category = _('View')},
		{combos = {{key = 'S', reformers = {'LCtrl'}}}, pressed = iCommandViewKeyLCtrlS, up = iCommandViewKeyLCtrlSStop, name = _('Slow backward key LCtrl-S'), category = _('View')},
		{combos = {{key = 'A', reformers = {'LCtrl'}}}, pressed = iCommandViewKeyLCtrlA, up = iCommandViewKeyLCtrlAStop, name = _('Slow left key LCtrl-A'), category = _('View')},
		{combos = {{key = 'D', reformers = {'LCtrl'}}}, pressed = iCommandViewKeyLCtrlD, up = iCommandViewKeyLCtrlDStop, name = _('Slow right key LCtrl-D'), category = _('View')},
		{combos = {{key = 'E'}}, pressed = iCommandViewCameraHeightUp, up = iCommandViewCameraHeightUpStop, name = _('Camera height up'), category = _('View')},
		{combos = {{key = 'E', reformers = {'LShift'}}}, pressed = iCommandViewCameraHeightUpFast, up = iCommandViewCameraHeightUpStop, name = _('Camera height up fast'), category = _('View')},
		{combos = {{key = 'E', reformers = {'LCtrl'}}}, pressed = iCommandViewCameraHeightUpSlow, up = iCommandViewCameraHeightUpStop, name = _('Camera height up slow'), category = _('View')},
		{combos = {{key = 'Q'}}, pressed = iCommandViewCameraHeightDown, up = iCommandViewCameraHeightDownStop, name = _('Camera height down'), category = _('View')},
		{combos = {{key = 'Q', reformers = {'LShift'}}}, pressed = iCommandViewCameraHeightDownFast, up = iCommandViewCameraHeightDownStop, name = _('Camera height down fast'), category = _('View')},
		{combos = {{key = 'Q', reformers = {'LCtrl'}}}, pressed = iCommandViewCameraHeightDownSlow, up = iCommandViewCameraHeightDownStop, name = _('Camera height down slow'), category = _('View')},

		{combos = {{key = 'Num5', reformers = {'RShift'}}}, down = iCommandViewCameraToHorizont, name = _('Align camera to the Earth horizont'), category = _('View')},
		{combos = {{key = 'Num4'}}, pressed = iCommandViewLeft, up = iCommandViewLeftStop, name = _('F11 camera yaw left'), category = _('View')},
		{combos = {{key = 'Num6'}}, pressed = iCommandViewRight, up = iCommandViewRightStop, name = _('F11 camera yaw right'), category = _('View')},
		{combos = {{key = 'Num8'}}, pressed = iCommandViewUp, up = iCommandViewUpStop, name = _('F11 camera pitch up'), category = _('View')},
		{combos = {{key = 'Num2'}}, pressed = iCommandViewDown, up = iCommandViewDownStop, name = _('F11 camera pitch down'), category = _('View')},
		{combos = {{key = 'Num4', reformers = {'RShift'}}}, pressed = iCommandViewLeftFast, up = iCommandViewLeftStop, name = _('F11 camera yaw left fast'), category = _('View')},
		{combos = {{key = 'Num6', reformers = {'RShift'}}}, pressed = iCommandViewRightFast, up = iCommandViewRightStop, name = _('F11 camera yaw right fast'), category = _('View')},
		{combos = {{key = 'Num8', reformers = {'RShift'}}}, pressed = iCommandViewUpFast, up = iCommandViewUpStop, name = _('F11 camera pitch up fast'), category = _('View')},
		{combos = {{key = 'Num2', reformers = {'RShift'}}}, pressed = iCommandViewDownFast, up = iCommandViewDownStop, name = _('F11 camera pitch down fast'), category = _('View')},
		{combos = {{key = 'Num4', reformers = {'RCtrl'}}}, pressed = iCommandViewLeftSlow, up = iCommandViewLeftStop, name = _('F11 camera yaw left slow'), category = _('View')},
		{combos = {{key = 'Num6', reformers = {'RCtrl'}}}, pressed = iCommandViewRightSlow, up = iCommandViewRightStop, name = _('F11 camera yaw right slow'), category = _('View')},
		{combos = {{key = 'Num8', reformers = {'RCtrl'}}}, pressed = iCommandViewUpSlow, up = iCommandViewUpStop, name = _('F11 camera pitch up slow'), category = _('View')},
		{combos = {{key = 'Num2', reformers = {'RCtrl'}}}, pressed = iCommandViewDownSlow, up = iCommandViewDownStop, name = _('F11 camera pitch down slow'), category = _('View')},
		{combos = {{key = 'Num1'}}, pressed = iCommandViewDownLeft, up = iCommandViewDownLeftStop, name = _('F11 camera pitch down, yaw left'), category = _('View')},
		{combos = {{key = 'Num3'}}, pressed = iCommandViewDownRight, up = iCommandViewDownRightStop, name = _('F11 camera pitch down, yaw right'), category = _('View')},
		{combos = {{key = 'Num7'}}, pressed = iCommandViewUpLeft, up = iCommandViewUpLeftStop, name = _('F11 camera pitch up, yaw left'), category = _('View')},
		{combos = {{key = 'Num9'}}, pressed = iCommandViewUpRight, up = iCommandViewUpRightStop, name = _('F11 camera pitch up, yaw right'), category = _('View')},
		{combos = {{key = 'Num1', reformers = {'RShift'}}}, pressed = iCommandViewDownLeftFast, up = iCommandViewDownLeftStop, name = _('F11 camera pitch down, yaw left fast'), category = _('View')},
		{combos = {{key = 'Num3', reformers = {'RShift'}}}, pressed = iCommandViewDownRightFast, up = iCommandViewDownRightStop, name = _('F11 camera pitch down, yaw right fast'), category = _('View')},
		{combos = {{key = 'Num7', reformers = {'RShift'}}}, pressed = iCommandViewUpLeftFast, up = iCommandViewUpLeftStop, name = _('F11 camera pitch up, yaw left fast'), category = _('View')},
		{combos = {{key = 'Num9', reformers = {'RShift'}}}, pressed = iCommandViewUpRightFast, up = iCommandViewUpRightStop, name = _('F11 camera pitch up, yaw right fast'), category = _('View')},
		{combos = {{key = 'Num1', reformers = {'RCtrl'}}}, pressed = iCommandViewDownLeftSlow, up = iCommandViewDownLeftStop, name = _('F11 camera pitch down, yaw left slow'), category = _('View')},
		{combos = {{key = 'Num3', reformers = {'RCtrl'}}}, pressed = iCommandViewDownRightSlow, up = iCommandViewDownRightStop, name = _('F11 camera pitch down, yaw right slow'), category = _('View')},
		{combos = {{key = 'Num7', reformers = {'RCtrl'}}}, pressed = iCommandViewUpLeftSlow, up = iCommandViewUpLeftStop, name = _('F11 camera pitch up, yaw left slow'), category = _('View')},
		{combos = {{key = 'Num9', reformers = {'RCtrl'}}}, pressed = iCommandViewUpRightSlow, up = iCommandViewUpRightStop, name = _('F11 camera pitch up, yaw right slow'), category = _('View')},
	},
}
