return {
	keyCommands = {
		{combos = {{key = 'M'}}, down = iCommandViewMainMenuBar, name = _('Camera main menu bar'), category =  _('View')},
		{combos = {{key = 'Z'}}, down = iCommandViewBookmarksEditor, name = _('Camera bookmarks editor'), category =  _('View')},
		{combos = {{key = 'O'}}, down = iCommandViewPieMenu, name = _('Pie menu'), category = _('View')},
		{combos = {{key = 'H', reformers = {'LAlt'}}}, down = iCommandViewCameraMoveHorizontal, name = _('Horizontal camera moving'), category = _('View')},
		{combos = {{key = 'V', reformers = {'LAlt'}}}, down = iCommandViewCameraMoveVertical, name = _('Vertical camera moving'), category = _('View')},
		{combos = {{key = 'F', reformers = {'LAlt'}}}, down = iCommandViewCameraMoveFrontal, name = _('Frontal camera moving'), category = _('View')},
		{combos = {{key = 'G', reformers = {'LAlt'}}}, down = iCommandViewAtGround, name = _('Direct the camera towards the ground'), category = _('View')},
		{combos = {{key = 'N', reformers = {'LAlt'}}}, down = iCommandViewCameraMoveAlongTheWalls, name = _('Direct the camera along the room walls'), category = _('View')},
		-- WASDEQ keys
		{combos = {{key = 'W'}}, pressed = iCommandViewKeyW, up = iCommandViewKeyWStop, name = _('Forward key W'), category = _('View')},
		{combos = {{key = 'S'}}, pressed = iCommandViewKeyS, up = iCommandViewKeySStop, name = _('Backward key S'), category = _('View')},
		{combos = {{key = 'A'}}, pressed = iCommandViewKeyA, up = iCommandViewKeyAStop, name = _('Left key A'), category = _('View')},
		{combos = {{key = 'D'}}, pressed = iCommandViewKeyD, up = iCommandViewKeyDStop, name = _('Right key D'), category = _('View')},
		{combos = {{key = 'W', reformers = {'LShift'}}}, pressed = iCommandViewKeyLShiftW, up = iCommandViewKeyLShiftWStop, name = _('Fast forward key LShift-W'), category = _('View')},
		{combos = {{key = 'S', reformers = {'LShift'}}}, pressed = iCommandViewKeyLShiftS, up = iCommandViewKeyLShiftSStop, name = _('Fast backward key LShift-S'), category = _('View')},
		{combos = {{key = 'A', reformers = {'LShift'}}}, pressed = iCommandViewKeyLShiftA, up = iCommandViewKeyLShiftAStop, name = _('Fast left key LShift-A'), category = _('View')},
		{combos = {{key = 'D', reformers = {'LShift'}}}, pressed = iCommandViewKeyLShiftD, up = iCommandViewKeyLShiftDStop, name = _('Fast right key LShift-D'), category = _('View')},
		{combos = {{key = 'W', reformers = {'LCtrl'}}}, pressed = iCommandViewKeyLCtrlW, up = iCommandViewKeyLCtrlWStop, name = _('Slow forward key LCtrl-W'), category = _('View')},
		{combos = {{key = 'S', reformers = {'LCtrl'}}}, pressed = iCommandViewKeyLCtrlS, up = iCommandViewKeyLCtrlSStop, name = _('Slow backward key LCtrl-S'), category = _('View')},
		{combos = {{key = 'A', reformers = {'LCtrl'}}}, pressed = iCommandViewKeyLCtrlA, up = iCommandViewKeyLCtrlAStop, name = _('Slow left key LCtrl-A'), category = _('View')},
		{combos = {{key = 'D', reformers = {'LCtrl'}}}, pressed = iCommandViewKeyLCtrlD, up = iCommandViewKeyLCtrlDStop, name = _('Slow right key LCtrl-D'), category = _('View')},
		{combos = {{key = 'E'}}, pressed = iCommandViewCameraHeightUp, up = iCommandViewCameraHeightUpStop, name = _('Camera height up'), category = _('View')},
		{combos = {{key = 'E', reformers = {'LShift'}}}, pressed = iCommandViewCameraHeightUpFast, up = iCommandViewCameraHeightUpStop, name = _('Camera height up fast'), category = _('View')},
		{combos = {{key = 'E', reformers = {'LCtrl'}}}, pressed = iCommandViewCameraHeightUpSlow, up = iCommandViewCameraHeightUpStop, name = _('Camera height up slow'), category = _('View')},
		{combos = {{key = 'Q'}}, pressed = iCommandViewCameraHeightDown, up = iCommandViewCameraHeightDownStop, name = _('Camera height down'), category = _('View')},
		{combos = {{key = 'Q', reformers = {'LShift'}}}, pressed = iCommandViewCameraHeightDownFast, up = iCommandViewCameraHeightDownStop, name = _('Camera height down fast'), category = _('View')},
		{combos = {{key = 'Q', reformers = {'LCtrl'}}}, pressed = iCommandViewCameraHeightDownSlow, up = iCommandViewCameraHeightDownStop, name = _('Camera height down slow'), category = _('View')},
	},
}
